### ISSUE TITLE
Version 5 release

### ISSUE THREAD

**Issue by starkers** [bitnami/bitnami-docker-oauth2-proxy#11]
**Description**

All versions prior to v5 of are effected by a nasty [open redirect vulnerability](https://github.com/pusher/oauth2_proxy/security/advisories/GHSA-qqxw-m5fj-f7gv)

Please update https://github.com/pusher/oauth2_proxy/releases

**Comment by beltran-rubo** [comment]
Thanks, we are actively working on it. We will keep you in the loop.

**Comment by alemorcuq** [comment]
Thank you, @starkers. We just released version 5. Let us know if you find any issues with it.

**Comment by starkers** [comment]
Fantastic stuff, thanks for the quick turn around
