### ISSUE TITLE
Upgrade to version 6

### ISSUE THREAD

**Issue by cccs-cat001** [bitnami/bitnami-docker-oauth2-proxy#14]
Any chance you can upgrade this to oauth2-proxy version 6 which was released a few days ago? It fixes the deprecated azure AD graph issue.

**Comment by rafariossaa** [comment]
Hi @cccs-cat001 ,
  We are currently working in releasing oauth2-proxy, it should be out in the next weeks.

**Comment by cccs-cat001** [comment]
Thank you :)

**Comment by rafariossaa** [comment]
You are welcome.
I am closing this issue by now.
