### ISSUE TITLE
Wrong configuration section in the README

### ISSUE THREAD

**Issue by andresmgot** [bitnami/bitnami-docker-oauth2-proxy#17]
**Description**

It seems that the [Configuration](https://github.com/bitnami/bitnami-docker-oauth2-proxy#configuration) section of the README is showing some content related to Prometheus exporters, rather than info of how to configure oauth2_proxy.

**Comment by Mauraza** [comment]
Hi @andresmgot 

thanks a lot for the contribution!, this will be fixed in the next revision.

**Comment by andresmgot** [comment]
This can be closed now, thanks!
