### ISSUE TITLE
Ownership issue

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/bitnami-docker-oauth2-proxy#22]
### Name and Version

bitnami/oauth2-proxy:7.2.1-debian-10-r115

### What steps will reproduce the bug?

1. Run the image.
2. Notice that files is owned by user 1000 (path: /opt/bitnami )
3. Check Dockerfile, it indicates that it should run (and be owned) by user 1001

### What is the expected behavior?

Files being owned by user 1001 and process running as 1001.
Instead of files being owned by user 1000 and process running as 1001.

### What do you see instead?

That either the files are owned by 1001 or the process is running as 1000

### Additional information

Please check https://github.com/bitnami/bitnami-docker-fluent-bit/issues/4 explaining the same issue, just for fluent-bit.

**Comment by jotamartos** [comment]
Hi @nc-ruth,

Thank you for taking the time to report this. We are going to apply the same change we made in https://github.com/bitnami/bitnami-docker-fluent-bit/issues/4. Once the image is released, we will let you know and close this issue. 

Thanks

**Comment by jotamartos** [comment]
Hi again @nc-ruth,

Version `7.2.1-debian-10-r122` fixes this. Please pull the latest tag or get that specific version and deploy the solution again.

Thanks.
