### ISSUE TITLE
OpenID Connect support

### ISSUE THREAD

**Issue by falfaro** [bitnami/bitnami-docker-oauth2-proxy#4]
Does Bitnami's oauth2-proxy tagged 2.2.0-r15 OpenID connect?
On a version compiled from upstream, there is support for a flag named "--oidc-issuer-url=" but 2.2.0-r15 does not seem to support it:

```
authproxy    | flag provided but not defined: -oidc-issuer-url
```

Any chance of getting OpenID connect support baked in?

**Comment by tompizmor** [comment]
It seems the latest version of the oauth2-proxy plugin still does not include that feature that it is present in the master branch. I see you already create an issue in the oauth2-proxy repo (https://github.com/bitly/oauth2_proxy/issues/634) so let's see if they can create a new release.
