### ISSUE TITLE
latest build (day ago) oauth2-proxy hang after 2-3h

### ISSUE THREAD

**Issue by mkyc** [bitnami/bitnami-docker-oauth2-proxy#5]
**Description**

oauth2-proxy hanged after about 3 hours of work when using latest build on environment 

**Steps to reproduce the issue:**

start kubernetes app from latest build
wait 2-4 hours

**Describe the results you received:**

initial get to oauth2-proxy gets 500: 

````
500 Internal Server Error 
--------
nginx/1.13.12
````

**Describe the results you expected:**

redirect to oauthprovider or to service

**Additional information you deem important (e.g. issue happens only occasionally):**

it takes 2-3 hours to code 500 start to happen. 

**Container version:**
````
0.20180625.74543
````
Previous versions work. 

**All the logs from container when it wasn't even used:**

````
2018/09/07 13:07:30 validator.go:23: using authenticated emails file /emails_allowed.conf
2018/09/07 13:07:30 watcher.go:66: watching /emails_allowed.conf for updates
2018/09/07 13:07:30 oauthproxy.go:143: mapping path "/dev/null" => file system "/dev/null"
2018/09/07 13:07:30 oauthproxy.go:157: OAuthProxy configured for Azure Client ID: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2018/09/07 13:07:30 oauthproxy.go:163: Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domain: refresh:disabled
2018/09/07 13:07:30 http.go:49: HTTP: listening on 0.0.0.0:4180
````

**Comment by tompizmor** [comment]
Could you please let us know the specific tags of the docker images? 
We will try to check any difference but in there has not been any change in the oauth2 component in the latest releases. 
We have simply updated some system packages.

**Comment by mkyc** [comment]
it must have been 0.20180625.74543-r26 but I'm not 100% sure right now. I'll check on newest builds in following days if it still occurs.

**Comment by tompizmor** [comment]
Ok! Let us know if you reproduce it again!
