### ISSUE TITLE
What is the upstream source for the oauth2-proxy codebase?

### ISSUE THREAD

**Issue by sellers** [bitnami/bitnami-docker-oauth2-proxy#6]
Given that bitly's source base has become stale, I see that this docker create is pulling an image from bitnami downloads for the oauth2-proxy code.   Is that code available for view so we can determine what features and PRs have been added to the code and which have not?  (e.g. some of the PRs for bitly are useful including the ability to pass a bearer token which Pusher added).  

Thanks for sharing your work.

**Comment by juan131** [comment]
Hi @sellers 

As you mentioned, https://github.com/bitly/oauth2_proxy became stale. We're currently retrieving the source code from: https://github.com/giantswarm/docker-oauth2-proxy

However, we didn't modify the **REAMDE.md** file to state that change. Thanks for reporting it, I'll update the **REAMDE.md** file

**Comment by juan131** [comment]
Hi @sellers 

We're not base on https://github.com/bitly/oauth2_proxy repository anymore.  The latest versions are based on the code available at https://github.com/giantswarm/oauth2_prox

I'll update the **README.md** to state those changes.

**Comment by sellers** [comment]
Thanks.  Looks like that fork is read-only, but thanks for sharing the origin.
