### ISSUE TITLE
Upstream is unmaintained

### ISSUE THREAD

**Issue by jamielennox** [bitnami/bitnami-docker-oauth2-proxy#7]
https://github.com/giantswarm/oauth2_proxy is in archive more and assumedly won't be receiving any further updates. I'm not aware of any problems with the code, but I'm seeing it used more and more in kubernetes clusters and I'm wondering if there's been a discussion as to where this development goes now?

**Comment by jamielennox** [comment]
Ah, lots of discussion https://github.com/bitly/oauth2_proxy/issues/628#issuecomment-417121636 just not on the fork.

So of concern as I found this package referenced from the bitnami kubernetes production runtime stack.

**Comment by juan131** [comment]
cc/ @falfaro @anguslees

**Comment by juan131** [comment]
Hi @jamielennox 

We're already aware of this issue and we're discussing the best alternative to use on the issue below:
https://github.com/bitnami/kube-prod-runtime/issues/229

**Comment by jamielennox** [comment]
Perfect, thanks.
